import { Language } from './types';

export const UI_TEXT = {
  [Language.EN]: {
    title: 'AI Posing Assistant',
    recreateMode: 'Recreate Pose',
    improveMode: 'Improve Scene',
    recreateDescription: 'Upload a target pose and your photo. AI will guide you.',
    improveDescription: 'Upload a scene. AI will suggest improvements and poses.',
    targetImage: 'Target Pose Image',
    yourImage: 'Your Image',
    sceneImage: 'Scene Image',
    uploadInstruction: 'Click to upload or drag and drop',
    changeImage: 'Change Image',
    generate: 'Generate Advice',
    generating: 'Generating...',
    aiResponseTitle: 'AI Suggestions',
    conceptsTitle: 'Creative Concepts',
    errorTitle: 'An Error Occurred',
    errorInstruction: 'Please check your images and try again. Ensure you have a valid API Key setup.',
    selectMode: 'Select a mode to begin',
    generateDemo: 'Generate Demo Image',
    demoImageTitle: 'Suggested Scene',
    camera: 'Camera',
    upload: 'Upload',
    capture: 'Capture',
    cameraError: 'Could not access camera. Please check permissions.',
  },
  [Language.VI]: {
    title: 'Trợ lý Tạo Dáng AI',
    recreateMode: 'Tái tạo Dáng',
    improveMode: 'Cải thiện Cảnh',
    recreateDescription: 'Tải ảnh mẫu và ảnh của bạn. AI sẽ hướng dẫn bạn.',
    improveDescription: 'Tải ảnh một khung cảnh. AI sẽ gợi ý cách cải thiện và tạo dáng.',
    targetImage: 'Ảnh Dáng Mẫu',
    yourImage: 'Ảnh Của Bạn',
    sceneImage: 'Ảnh Chụp Cảnh',
    uploadInstruction: 'Nhấn để tải lên hoặc kéo thả',
    changeImage: 'Đổi ảnh',
    generate: 'Tạo Gợi Ý',
    generating: 'Đang tạo...',
    aiResponseTitle: 'Gợi ý từ AI',
    conceptsTitle: 'Các concept Sáng tạo',
    errorTitle: 'Đã xảy ra lỗi',
    errorInstruction: 'Vui lòng kiểm tra lại ảnh và thử lại. Đảm bảo bạn đã thiết lập API Key hợp lệ.',
    selectMode: 'Chọn một chế độ để bắt đầu',
    generateDemo: 'Tạo ảnh minh họa',
    demoImageTitle: 'Cảnh được gợi ý',
    camera: 'Máy ảnh',
    upload: 'Tải lên',
    capture: 'Chụp',
    cameraError: 'Không thể truy cập máy ảnh. Vui lòng kiểm tra quyền.',
  }
};
